# Generated by Django 4.0.1 on 2022-01-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='unique_key',
            field=models.CharField(default=8704, editable=False, max_length=7),
        ),
    ]
